apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-ddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs 
  template: 
    metadata:
      labels: 
        app: nodejs 
    spec: 
      containers: 
      - name: nodejs 
        image: shiva185/devops-portfolio:latest
        ports: 
        - containerPort: 3000